name: CI

on: ["push", "pull_request"]


jobs:
    lint:
        runs-on: ubuntu-latest
        steps:

            - uses: actions/checkout@v1

            - name: Use Node.js 12.x
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x

            - name: npm install, make test-coverage
              run: |
                  npm install
                  npm run lint

    test:
        runs-on: ubuntu-latest
        steps:

            - uses: actions/checkout@v1

            - name: Use Node.js 12.x
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x

            - name: npm install, make test-coverage
              run: |
                  npm install
                  npm run test-coverage

            - name: Coveralls
              uses: coverallsapp/github-action@master
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
    build:
        runs-on: ubuntu-latest
        steps:

            - uses: actions/checkout@v1

            - name: Use Node.js 12.x
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x

            - name: npm install, make test-coverage
              run: |
                  npm install
                  npm run build:prod